ALTER TABLE Tickets
	ADD FOREIGN KEY (theaterID,showingDate,startTime)
	REFERENCES Showings
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE Tickets
	ADD FOREIGN KEY (customerID)
	REFERENCES Customers
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE Tickets
	ADD FOREIGN KEY (theaterID,seatNum)
	REFERENCES TheaterSeats
	ON DELETE CASCADE
	ON UPDATE CASCADE;


